CREATE EXTENSION IF NOT EXISTS citext;


CREATE TYPE archetype_enum AS ENUM (
    '"C"',
    '-Eyes Dragon',
    '25th Anniversary Monsters',
    '@Ignister',
    'A-to-Z',
    'A.I.',
    'ABC',
    'Abyss Actor',
    'Abyss Script',
    'Abyss-',
    'Adamancipator',
    'Advanced Crystal Beast',
    'Adventurer',
    'Adventurer Token',
    'Aesir',
    'Aether',
    'Albaz Dragon',
    'Alien',
    'Alligator',
    'Allure Queen',
    'Ally of Justice',
    'Altergeist',
    'Amazement',
    'Amazoness',
    'Amorphage',
    'Ancient Fairy Dragon',
    'Ancient Gear',
    'Ancient Treasure',
    'Ancient Warriors',
    'Anotherverse',
    'Anti',
    'Apophis',
    'Apoqliphort',
    'Appliancer',
    'Aqua Jet',
    'Aquaactress',
    'Aquamirror',
    'Arcana Force',
    'Archfiend',
    'Argostars',
    'Armed Dragon',
    'Aroma',
    'Artifact',
    'Artmage',
    'Ashened',
    'Assault Mode',
    'Atlantean',
    'Attraction',
    'Attribute Summoner',
    'Azamina',
    'B.E.S.',
    'Bamboo Sword',
    'Barbaros',
    'Barian''s',
    'Batteryman',
    'Battleguard',
    'Battlewasp',
    'Battlin'' Boxer',
    'Battlin'' Boxing',
    'Beetrooper',
    'Black Luster Soldier',
    'Blackwing',
    'Blaze Accelerator',
    'Blue Tears',
    'Blue-Eyes',
    'Bonding',
    'Book of',
    'Boot-Up',
    'Borrel',
    'Bounzer',
    'Branded',
    'Broken World',
    'Bugroth',
    'Bujin',
    'Burning Abyss',
    'Butterfly',
    'Butterspy',
    'Bystial',
    'CXyz',
    'Cataclysmic',
    'Celebration',
    'Celtic Guard',
    'Centur-Ion',
    'Chaos',
    'Chaos Phantom',
    'Charmer',
    'Chemicritter',
    'Chimera',
    'Chronomaly',
    'Chrysalis',
    'Cipher',
    'Circular',
    'Clear',
    'Clear Wing',
    'Cloudian',
    'Code Talker',
    'Codebreaker',
    'Constellar',
    'Contact',
    'Corn',
    'Cosmic Synchro Monster',
    'Counter Fairy',
    'Crusadia',
    'Crystal',
    'Crystal Beast',
    'Crystron',
    'Cubic',
    'Cupid',
    'Curse of Dragon',
    'Cyber',
    'Cyber Angel',
    'Cyber Dragon',
    'Cyberdark',
    'Cynet',
    'D.D.',
    'D/D',
    'Danger!',
    'Dark Contract',
    'Dark Magician',
    'Dark Scorpion',
    'Dark World',
    'Dark counterpart',
    'Darklord',
    'Deep Sea',
    'Demise',
    'Deskbot',
    'Despia',
    'Destiny HERO',
    'Destruction Sword',
    'Diabell',
    'Diabellstar',
    'Dice',
    'Digital Bug',
    'Dinomist',
    'Dinomorphia',
    'Dinowrestler',
    'Divine Dragon',
    'Djinn',
    'Dododo',
    'Dogmatika',
    'Doll',
    'Doll Monster',
    'Dominus',
    'Doodle Beast',
    'Doodlebook',
    'Doom-Z',
    'Doriado',
    'Draconia',
    'Dracoslayer',
    'Dracotail',
    'Dracoverlord',
    'Dragon Ruler',
    'Dragonmaid',
    'Dragunity',
    'Dream Mirror',
    'Drytron',
    'Dual Avatar',
    'Duston',
    'Earthbound',
    'Edge Imp',
    'Egyptian God',
    'Eldlich',
    'Eldlixir',
    'Elemental HERO',
    'Elemental Lord',
    'Elementsaber',
    'Emblema',
    'Empower',
    'Empowered Warrior',
    'Endymion',
    'Enneacraft',
    'Evil Eye',
    'Evil HERO',
    'Evil★Twin',
    'Evol',
    'Evolsaur',
    'Evoltile',
    'Evolzar',
    'Exchange of the Spirit',
    'Exodd',
    'Exodia',
    'Exosister',
    'Eyes Restrict',
    'F.A.',
    'Fabled',
    'Fairy',
    'Fairy Tail',
    'Fan-Made Cards',
    'Favorite',
    'Felgrand',
    'Field Searcher',
    'Fiendsmith',
    'Fire Fist',
    'Fire Formation',
    'Fire King',
    'Firewall',
    'Fishborg',
    'Flame Swordsman',
    'Flamvell',
    'Fleur',
    'Floowandereeze',
    'Flower Cardian',
    'Fluffal',
    'Forbidden',
    'Fortress Whale',
    'Fortune Fairy',
    'Fortune Lady',
    'Fossil',
    'Frightfur',
    'Frog',
    'From the Underworld',
    'Fur Hire',
    'Fusion',
    'G Golem',
    'Gadget',
    'Gagaga',
    'Gaia Knight',
    'Gaia The Fierce Knight',
    'Galaxy',
    'Galaxy-Eyes',
    'Gandora',
    'Gate Guardian',
    'Geargia',
    'Gem Dragon',
    'Gem-',
    'Generaider',
    'Genex',
    'Ghostrick',
    'Ghoti',
    'Gimmick Puppet',
    'Gishki',
    'Gizmek',
    'Glacial Beast',
    'Gladiator',
    'Gladiator Beast',
    'Goblin',
    'Gogogo',
    'Gold Pride',
    'Golden Castle of Stromberg',
    'Golden Land',
    'Gorgonic',
    'Gouki',
    'GranSolfachord',
    'Gravekeeper''s',
    'Graydle',
    'Greed',
    'Grepher',
    'Guardian',
    'Guardragon',
    'Gunkan',
    'Gusto',
    'HERO',
    'Harpie',
    'Hazy',
    'Heart',
    'Hecahands',
    'Herald',
    'Heraldic',
    'Heraldry',
    'Heroic',
    'Hi-Speedroid',
    'Hieratic',
    'Hole',
    'Holy Knight',
    'Horus',
    'Horus the Black Flame Dragon',
    'Hyperion',
    'Ice Barrier',
    'Icejade',
    'Igknight',
    'Impcantation',
    'Indestructible Insect',
    'Infernity',
    'Infernoble Arms',
    'Infernoble Knight',
    'Infernoid',
    'Infestation',
    'Infinitrack',
    'Invoked',
    'Inzektor',
    'Iron Chain',
    'Jar',
    'Jester',
    'Jinzo',
    'Junk',
    'Jurrac',
    'K9',
    'Kaiju',
    'Kairyu-Shin',
    'Karakuri',
    'Kashtira',
    'Ki-sikil',
    'Killer Tune',
    'Knight',
    'Knightmare',
    'Koa''ki Meiru',
    'Koala',
    'Konami Arcade Games',
    'Kozmo',
    'Krawler',
    'Kuriboh',
    'Labrynth',
    'Labyrinth Wall',
    'Lady of Lament',
    'Laval',
    'Legendary Knight',
    'Libromancer',
    'Light and Darkness Dragon',
    'Lightsworn',
    'Lil-la',
    'Live☆Twin',
    'Lswarm',
    'Lunalight',
    'Lyrilusc',
    'Machina',
    'Machine Angel',
    'Madolche',
    'Madoor',
    'Magical Musket',
    'Magician',
    'Magician Girl',
    'Magikey',
    'Magistus',
    'Magnet Warrior',
    'Magnifistorm',
    'Majespecter',
    'Majestic',
    'Maju',
    'Malefic',
    'Malicevorous',
    'Maliss',
    'Man-Eater Bug',
    'Mannadium',
    'Marincess',
    'Martial Art Spirit',
    'Mask',
    'Masked HERO',
    'Materiactor',
    'Mathmech',
    'Mayakashi',
    'Mecha Phantom Beast',
    'Megalith',
    'Mekk-Knight',
    'Meklord',
    'Melffy',
    'Melodious',
    'Memento',
    'Mermail',
    'Metalfoes',
    'Metalmorph',
    'Metaphys',
    'Mikanko',
    'Millennium',
    'Mimighoul',
    'Mirror Trap',
    'Mist Valley',
    'Mitsurugi',
    'Mokey Mokey',
    'Monarch',
    'Morganite',
    'Morphtronic',
    'Motor',
    'Mulcharmy',
    'Mystical Beast of the Forest',
    'Mythical Beast',
    'Myutant',
    'Naturia',
    'Nekroz',
    'Nemeses',
    'Nemleria',
    'Nemurelia',
    'Neo Space',
    'Neo-Spacian',
    'Neos',
    'Nephthys',
    'Nimble',
    'Ninja',
    'Ninjitsu Art',
    'Noble Arms',
    'Noble Knight',
    'Nordic',
    'Nouvelles',
    'Number',
    'Numeron',
    'Odd-Eyes',
    'Ogdoadic',
    'Ojama',
    'Onomat',
    'Orcust',
    'Overlay',
    'P.U.N.K.',
    'PSY-Frame',
    'Paladins of Dragons',
    'Paleozoic',
    'PaniK''s monsters',
    'Parasite',
    'Parshath',
    'Patissciel',
    'Pendulum',
    'Pendulum Dragon',
    'Penguin',
    'Performage',
    'Performapal',
    'Phantasm',
    'Phantasm Spiral',
    'Phantom Beast',
    'Phantom Knights',
    'Photon',
    'Plunder Patroll',
    'Polymerization',
    'Possessed',
    'Potan',
    'Power Patron',
    'Power Tool',
    'Prank-Kids',
    'Predap',
    'Predaplant',
    'Prediction Princess',
    'Priestess',
    'Primite',
    'Prophecy',
    'Puppet',
    'Purrely',
    'Qli',
    'R.B.',
    'Ra',
    'Ragnaraika',
    'Raidraptor',
    'Rainbow Bridge',
    'Rank-Up-Magic',
    'Recipe',
    'Recolored counterpart',
    'Red-Eyes',
    'Regenesis',
    'Relinquished',
    'Reptilianne',
    'Rescue Squad',
    'Rescue-ACE',
    'Resonator',
    'Rikka',
    'Risebell',
    'Ritual Beast',
    'Roid',
    'Rokket',
    'Roland',
    'Rose',
    'Rose Dragon',
    'Runick',
    'Ryu-Ge',
    'Ryzeal',
    'S-Force',
    'SPYRAL',
    'Saber',
    'Sacred Beast',
    'Salamandra',
    'Salamangreat',
    'Sangen',
    'Scareclaw',
    'Schoolwork',
    'Scrap',
    'Scrap-Iron',
    'Sea Stealth',
    'Secret Six Samurai',
    'Serket',
    'Seventh',
    'Shaddoll',
    'Shark',
    'Shining Sarcophagus',
    'Shinobird',
    'Shiranui',
    'Signature move',
    'Silent Magician',
    'Silent Swordsman',
    'Simorgh',
    'Sinful Spoils',
    'Six Samurai',
    'Six Strike',
    'Skilled Magician',
    'Skull Servant',
    'Sky Scourge',
    'Sky Striker',
    'Skyblaster',
    'Slime',
    'Snake-Eye',
    'Solemn',
    'Solfachord',
    'Speedroid',
    'Spellbook',
    'Sphinx',
    'Spider',
    'Spirit Message',
    'Spiritual Art',
    'Spright',
    'Springans',
    'Star',
    'Star Seraph',
    'Stardust',
    'Starliege',
    'Starry Knight',
    'Stealth Kragen',
    'Steelswarm',
    'Stellarknight',
    'Subterror',
    'Sunavalon',
    'Sunseed',
    'Sunvine',
    'Super Defense Robot',
    'Super Quant',
    'Superheavy',
    'Superheavy Samurai',
    'Supreme King',
    'Swarm of',
    'Swordsoul',
    'Sylvan',
    'Symphonic Warrior',
    'Synchro',
    'Synchron',
    'T.G.',
    'Tachyon',
    'Tearlaments',
    'Teleport',
    'Tellarknight',
    'Temple of the Kings',
    'Tenpai Dragon',
    'Tenyi',
    'Test',
    'The Agent',
    'The Sanctuary in the Sky',
    'The Weather',
    'Therion',
    'Thunder Dragon',
    'Tiki',
    'Time Thief',
    'Timelord',
    'Tindangle',
    'Tistina',
    'Toon',
    'Toy',
    'Train',
    'Transcendosaurus',
    'Trap Hole',
    'Trap Monster',
    'Traptrix',
    'Tri-Brigade',
    'Triamid',
    'Trickstar',
    'True Draco',
    'U.A.',
    'Umbral Horror',
    'Umi',
    'Unchained',
    'Underworld',
    'Uniform Nomenclature',
    'Ursarctic',
    'Utopia',
    'Utopic',
    'Vaalmonica',
    'Valkyrie',
    'Vampire',
    'Vanquish Soul',
    'Vassal',
    'Vaylantz',
    'Veda',
    'Vendread',
    'Venom',
    'Vernusylph',
    'Virtual World',
    'Visas',
    'Vision HERO',
    'Voiceless Voice',
    'Void',
    'Volcanic',
    'Vylon',
    'War Rock',
    'Warrior',
    'Watt',
    'Wedju',
    'White',
    'White Forest',
    'Wicked God',
    'Wight',
    'Wind-Up',
    'Windwitch',
    'Witchcrafter',
    'World Chalice',
    'World Legacy',
    'Worm',
    'X-Saber',
    'Xyz',
    'Yang Zing',
    'Yosenju',
    'Yubel',
    'Yummy',
    'Zefra',
    'Zera',
    'Zexal',
    'Zombie counterpart',
    'Zoodiac',
    'Zubaba',
    'hunder',
    'roid',
    'sphinx',
    'tellarknight',
    'with Eyes of Blue'
);

CREATE TYPE race_enum AS ENUM (
    'Abidos the Th',
    'Adrian Gecko',
    'Alexis Rhodes',
    'Amnael',
    'Andrew',
    'Aqua',
    'Arkana',
    'Aster Phoenix',
    'Axel Brodie',
    'Bastion Misaw',
    'Beast',
    'Beast-Warrior',
    'Bonz',
    'Camula',
    'Chazz Princet',
    'Christine',
    'Chumley Huffi',
    'Continuous',
    'Counter',
    'Creator God',
    'Cyberse',
    'David',
    'Dinosaur',
    'Divine-Beast',
    'Don Zaloog',
    'Dr. Vellian C',
    'Dragon',
    'Emma',
    'Equip',
    'Espa Roba',
    'Fairy',
    'Field',
    'Fiend',
    'Fish',
    'Illusion',
    'Insect',
    'Ishizu',
    'Ishizu Ishtar',
    'Jaden Yuki',
    'Jesse Anderso',
    'Joey',
    'Joey Wheeler',
    'Kagemaru',
    'Kaiba',
    'Keith',
    'Lumis Umbra',
    'Lumis and Umb',
    'Machine',
    'Mai',
    'Mai Valentine',
    'Mako',
    'Nightshroud',
    'Normal',
    'Odion',
    'Paradox Broth',
    'Pegasus',
    'Plant',
    'Psychic',
    'Pyro',
    'Quick-Play',
    'Reptile',
    'Rex',
    'Ritual',
    'Rock',
    'Sea Serpent',
    'Seto Kaiba',
    'Spellcaster',
    'Syrus Truesda',
    'Tania',
    'Tea Gardner',
    'The Supreme K',
    'Thelonious Vi',
    'Thunder',
    'Titan',
    'Tyranno Hassl',
    'Warrior',
    'Weevil',
    'Winged Beast',
    'Wyrm',
    'Yami Bakura',
    'Yami Marik',
    'Yami Yugi',
    'Yubel',
    'Yugi',
    'Zane Truesdal',
    'Zombie'
);


CREATE TYPE type_enum as ENUM (
    'Effect Monster',
    'Flip Effect Monster',
    'Flip Tuner Effect Monster',
    'Fusion Monster',
    'Gemini Monster',
    'Link Monster',
    'Normal Monster',
    'Normal Tuner Monster',
    'Pendulum Effect Fusion Monster',
    'Pendulum Effect Monster',
    'Pendulum Effect Ritual Monster',
    'Pendulum Flip Effect Monster',
    'Pendulum Normal Monster',
    'Pendulum Tuner Effect Monster',
    'Ritual Effect Monster',
    'Ritual Monster',
    'Skill Card',
    'Spell Card',
    'Spirit Monster',
    'Synchro Monster',
    'Synchro Pendulum Effect Monster',
    'Synchro Tuner Monster',
    'Token',
    'Toon Monster',
    'Trap Card',
    'Tuner Monster',
    'Union Effect Monster',
    'XYZ Monster',
    'XYZ Pendulum Effect Monster'
);


CREATE TYPE frametype_enum as ENUM (
    'effect',
    'effect_pendulum',
    'fusion',
    'fusion_pendulum',
    'link',
    'normal',
    'normal_pendulum',
    'ritual',
    'ritual_pendulum',
    'skill',
    'spell',
    'synchro',
    'synchro_pendulum',
    'token',
    'trap',
    'xyz',
    'xyz_pendulum'
);


CREATE TYPE attribute_enum AS ENUM (
    'DARK',
    'DIVINE',
    'EARTH',
    'FIRE',
    'LIGHT',
    'WATER',
    'WIND'
);


CREATE TYPE position_enum AS ENUM (
    'Bottom', 
    'Top', 
    'Left', 
    'Right',
    'Bottom-Left', 
    'Bottom-Right', 
    'Top-Left', 
    'Top-Right'
);

CREATE TYPE ban_type_enum AS ENUM (
    'Forbidden', 
    'Limited', 
    'Semi-Limited'
);

CREATE TYPE ban_org_enum AS ENUM (
    'ocg', 
    'tcg', 
    'goat'
);


CREATE TABLE IF NOT EXISTS set_rarity (
    set_rarity_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name citext NOT NULL UNIQUE,
    code TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


CREATE TABLE IF NOT EXISTS card_sets (
    card_set_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name citext NOT NULL,
    code TEXT NOT NULL,
    set_rarity_id INT DEFAULT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (set_rarity_id) REFERENCES set_rarity(set_rarity_id) ON DELETE SET NULL ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS cards (
    card_id INT PRIMARY KEY NOT NULL,
    name citext NOT NULL,
    descr TEXT NOT NULL,
    pend_descr TEXT,
    monster_desc TEXT,    
    attack INT,
    defence INT,
    level INT,
    archetype archetype_enum,
    attribute attribute_enum,
    frametype frametype_enum,
    race race_enum,
    type type_enum,
    created_at TIMESTAMPTZ DEFAULT NOW()    
);


CREATE TABLE IF NOT EXISTS linkmarkers (
    card_id INT PRIMARY KEY NOT NULL,
    position position_enum NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (card_id) REFERENCES cards(card_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT linkmarkers_cstr_unique UNIQUE (card_id, position)
);


CREATE TABLE IF NOT EXISTS banlist (
    card_id INT PRIMARY KEY NOT NULL,
    ban_org ban_org_enum NOT NULL,
    ban_type ban_type_enum NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    FOREIGN KEY (card_id) REFERENCES cards(card_id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT banlist_cstr_unique UNIQUE (card_id, ban_org, ban_type)
);


CREATE TABLE IF NOT EXISTS set_cards (
    card_id INT NOT NULL,
    card_set_id INT NOT NULL,
    total INT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT set_cards_cstr_pkey PRIMARY KEY (card_id, card_set_id),
    FOREIGN KEY (card_id) REFERENCES cards(card_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (card_set_id) REFERENCES card_sets(card_set_id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS card_images (
    card_id INT PRIMARY KEY,
    image_url TEXT DEFAULT NULL,
    image_url_cropped TEXT DEFAULT NULL,
    image_url_small TEXT DEFAULT NULL,
    FOREIGN KEY (card_id) REFERENCES cards(card_id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS card_prices (
    card_id INT PRIMARY KEY,
    amazon_price INT DEFAULT 0,
    cardmarket_price INT DEFAULT 0,
    coolstuffinc_price INT DEFAULT 0,
    ebay_price INT DEFAULT 0,
    tcgplayer_price INT DEFAULT 0,
    FOREIGN KEY (card_id) REFERENCES cards(card_id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger WHERE tgname = 'cards_updated_at'
    ) THEN
        CREATE TRIGGER cards_updated_at
        BEFORE UPDATE ON cards
        FOR EACH ROW
        EXECUTE FUNCTION update_updated_at_column();
    END IF;
END $$;